---
title: "Untitled"
author: "Guillermina Senn"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sp)
library(tmap)
library(sf)
library(rgdal)
```

```{r}
path <- '../data/external/data/descriptUnidadAnalisis/'
```

## Edaficas

```{r}
var_list = c('ARCILLA', 'ARENA', 'CC', 'CE', 'CEextsat')
```

```{r}
for (var in var_list){
  obj <- readOGR(
    dsn = paste(path, 
                'edafico/',
                var,
                '.gpkg',
                sep = ''),
    layer = var
  )
  var_name = paste('Media_', var, sep = '')
  print(qtm(obj, var_name))
}
```

## Sueltas

```{r}
var_list = c('LPD_descrpt')
```

```{r}
for (var in var_list){
  obj <- readOGR(
    dsn = paste(path, 
                var,
                '.gpkg',
                sep = ''),
    layer = var
  )
  var_name = paste('Media_', var, sep = '')
}

names(obj)
```

```{r}
qtm(obj, "Media_PEND")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```


```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```